### ISSUE TITLE
Uboot legacy error

### ISSUE THREAD

**Issue by Tron74** [orangepi-xunlong/u-boot-orangepi#3]
Hello,

when i try to compile legacy uboot for orange pi 3 i get this error: 

Configuring for sun50iw6p1 - Board: sun50iw6p1, Options: SUN50IW6P1
  GEN     include/autoconf.mk.dep
  GEN     include/autoconf.mk
  CHK     include/config/uboot.release
  CHK     include/generated/version_autogenerated.h
  CHK     include/generated/timestamp_autogenerated.h
  UPD     include/generated/timestamp_autogenerated.h
  CC      lib/asm-offsets.s
  GEN     include/generated/generic-asm-offsets.h
  CC      arch/arm/lib/asm-offsets.s
  GEN     include/generated/asm-offsets.h
  HOSTCC  tools/aisimage.o
[ error ] ERROR in function compile_uboot [ compilation.sh:217 ]
[ error ] U-boot compilation failed
[ o.k. ] Process terminated

Any suggestions? 
Thanks

**Comment by orangepi-xunlong** [comment]
You can check the log files in output /debug/ to see the error message.
