### ISSUE TITLE
uboot uboot no ethernet found

### ISSUE THREAD

**Issue by dawendiguo** [orangepi-xunlong/u-boot-orangepi#4]
I got a orangepi3 lts. when i use linux, the network is ok. but i try to use the uboot command nfs or some command which need the network, I got a message "no ethernet found", the "ping" command also return the same error.

I try to set the uboot enviriment, but it doesn't work. like this
```bash
setenv ipaddr 192.168.0.101
setenv ethaddr 00:04:9f:04:d2:35                           setenv gatewayip 192.168.0.1                               setenv netmask 255.255.255.0                               setenv serverip 192.168.2.107                              saveenv
```
uboot can get the right MAC address, but set ip address is not work

I am also sure the ip address and my host address is right, No fireware error, I can connect the ftp server in my phone.It sames as the orangepi3 lts doesn't connect to the network, 

So I want to ask "Is this uboot has network support?". or I need rebuild the uboot from the source? Is there some options must be set?

**Comment by orangepi-xunlong** [comment]
This function has not been adapted.
